export const PLAY_CARD_ACTIVITY = 'PLAY_CARD_ACTIVITY' as const;
export const TRASH_CARD_ACTIVITY = 'TRASH_CARD_ACTIVITY' as const;
export const DISCARD_CARD_ACTIVITY = 'DISCARD_CARD_ACTIVITY' as const;

