export const START_TURN_ACTIVITY = "START_TURN_ACTIVITY";
export const FINISH_TURN_ACTIVITY = "FINISH_TURN_ACTIVITY";

export const START_TURN_ACTION = "START_TURN_ACTION";
export const FINISH_TURN_ACTION = "FINISH_TURN_ACTION";
