export const ITEM_RESOURCE_TYPE = "ITEM_RESOURCE_TYPE";
export const EQUIP_ITEM_ACTIVITY = "EQUIP_ITEM_ACTIVITY";
export const MOVE_ITEM_ACTIVITY = "MOVE_ITEM_ACTIVITY";
export const USE_ITEM_ACTIVITY = "USE_ITEM_ACTIVITY";